all:; -(scons)

build-local:; -(scons)

clean:; -(scons -c)

diff-global:; -(git diff)

diff-local:; -(git diff .)

Gitk:; -(gitk --since="2 weeks ago")

Pull:; -(git pull)

Push:; -(git push)

Resolve-conflicts:; -(git mergetool -t kdiff3)

Status:; -(git status)

