import sys

# MAC -> darwin, Linux -> linux2
platform = sys.platform

if ( ('darwin' not in platform) and ('interix' not in platform)):
    SConscript('SConstruct.roboproc')
SConscript('SConstruct.asm')
